/**
 * This class is generated by jOOQ
 */
package de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DevelopersRecord extends org.jooq.impl.UpdatableRecordImpl<de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records.DevelopersRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -993024512;

	/**
	 * Setter for <code>reqbaz.developers.Id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>reqbaz.developers.Id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>reqbaz.developers.Requirement_Id</code>.
	 */
	public void setRequirementId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>reqbaz.developers.Requirement_Id</code>.
	 */
	public java.lang.Integer getRequirementId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>reqbaz.developers.User_Id</code>.
	 */
	public void setUserId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>reqbaz.developers.User_Id</code>.
	 */
	public java.lang.Integer getUserId() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Developers.DEVELOPERS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Developers.DEVELOPERS.REQUIREMENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Developers.DEVELOPERS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getRequirementId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DevelopersRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DevelopersRecord value2(java.lang.Integer value) {
		setRequirementId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DevelopersRecord value3(java.lang.Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DevelopersRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DevelopersRecord
	 */
	public DevelopersRecord() {
		super(de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Developers.DEVELOPERS);
	}

	/**
	 * Create a detached, initialised DevelopersRecord
	 */
	public DevelopersRecord(java.lang.Integer id, java.lang.Integer requirementId, java.lang.Integer userId) {
		super(de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Developers.DEVELOPERS);

		setValue(0, id);
		setValue(1, requirementId);
		setValue(2, userId);
	}
}
