/*
 * This file is generated by jOOQ.
*/
package de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records;


import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.PersonalisationData;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonalisationDataRecord extends UpdatableRecordImpl<PersonalisationDataRecord> implements Record7<Integer, Timestamp, Timestamp, String, Integer, Integer, String> {

    private static final long serialVersionUID = 1698925945;

    /**
     * Setter for <code>reqbaz.personalisation_data.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>reqbaz.personalisation_data.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>reqbaz.personalisation_data.creation_date</code>.
     */
    public void setCreationDate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>reqbaz.personalisation_data.creation_date</code>.
     */
    public Timestamp getCreationDate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>reqbaz.personalisation_data.last_updated_date</code>.
     */
    public void setLastUpdatedDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>reqbaz.personalisation_data.last_updated_date</code>.
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>reqbaz.personalisation_data.identifier</code>.
     */
    public void setIdentifier(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>reqbaz.personalisation_data.identifier</code>.
     */
    public String getIdentifier() {
        return (String) get(3);
    }

    /**
     * Setter for <code>reqbaz.personalisation_data.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>reqbaz.personalisation_data.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>reqbaz.personalisation_data.version</code>.
     */
    public void setVersion(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>reqbaz.personalisation_data.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>reqbaz.personalisation_data.setting</code>.
     */
    public void setSetting(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>reqbaz.personalisation_data.setting</code>.
     */
    public String getSetting() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Timestamp, Timestamp, String, Integer, Integer, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Timestamp, Timestamp, String, Integer, Integer, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PersonalisationData.PERSONALISATION_DATA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return PersonalisationData.PERSONALISATION_DATA.CREATION_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return PersonalisationData.PERSONALISATION_DATA.LAST_UPDATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return PersonalisationData.PERSONALISATION_DATA.IDENTIFIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return PersonalisationData.PERSONALISATION_DATA.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return PersonalisationData.PERSONALISATION_DATA.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return PersonalisationData.PERSONALISATION_DATA.SETTING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getLastUpdatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getSetting();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonalisationDataRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonalisationDataRecord value2(Timestamp value) {
        setCreationDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonalisationDataRecord value3(Timestamp value) {
        setLastUpdatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonalisationDataRecord value4(String value) {
        setIdentifier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonalisationDataRecord value5(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonalisationDataRecord value6(Integer value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonalisationDataRecord value7(String value) {
        setSetting(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonalisationDataRecord values(Integer value1, Timestamp value2, Timestamp value3, String value4, Integer value5, Integer value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PersonalisationDataRecord
     */
    public PersonalisationDataRecord() {
        super(PersonalisationData.PERSONALISATION_DATA);
    }

    /**
     * Create a detached, initialised PersonalisationDataRecord
     */
    public PersonalisationDataRecord(Integer id, Timestamp creationDate, Timestamp lastUpdatedDate, String identifier, Integer userId, Integer version, String setting) {
        super(PersonalisationData.PERSONALISATION_DATA);

        set(0, id);
        set(1, creationDate);
        set(2, lastUpdatedDate);
        set(3, identifier);
        set(4, userId);
        set(5, version);
        set(6, setting);
    }
}
