/**
 * This class is generated by jOOQ
 */
package de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RequirementsRecord extends org.jooq.impl.UpdatableRecordImpl<de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records.RequirementsRecord> implements org.jooq.Record9<java.lang.Integer, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp, java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 1703087933;

	/**
	 * Setter for <code>reqbaz.requirements.Id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>reqbaz.requirements.Id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>reqbaz.requirements.title</code>.
	 */
	public void setTitle(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>reqbaz.requirements.title</code>.
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>reqbaz.requirements.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>reqbaz.requirements.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>reqbaz.requirements.realized</code>.
	 */
	public void setRealized(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>reqbaz.requirements.realized</code>.
	 */
	public java.sql.Timestamp getRealized() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>reqbaz.requirements.creation_time</code>.
	 */
	public void setCreationTime(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>reqbaz.requirements.creation_time</code>.
	 */
	public java.sql.Timestamp getCreationTime() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>reqbaz.requirements.lastupdated_time</code>.
	 */
	public void setLastupdatedTime(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>reqbaz.requirements.lastupdated_time</code>.
	 */
	public java.sql.Timestamp getLastupdatedTime() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>reqbaz.requirements.Lead_developer_Id</code>.
	 */
	public void setLeadDeveloperId(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>reqbaz.requirements.Lead_developer_Id</code>.
	 */
	public java.lang.Integer getLeadDeveloperId() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>reqbaz.requirements.Creator_Id</code>.
	 */
	public void setCreatorId(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>reqbaz.requirements.Creator_Id</code>.
	 */
	public java.lang.Integer getCreatorId() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>reqbaz.requirements.Project_Id</code>.
	 */
	public void setProjectId(java.lang.Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>reqbaz.requirements.Project_Id</code>.
	 */
	public java.lang.Integer getProjectId() {
		return (java.lang.Integer) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp, java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp, java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Requirements.REQUIREMENTS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Requirements.REQUIREMENTS.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Requirements.REQUIREMENTS.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Requirements.REQUIREMENTS.REALIZED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Requirements.REQUIREMENTS.CREATION_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Requirements.REQUIREMENTS.LASTUPDATED_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Requirements.REQUIREMENTS.LEAD_DEVELOPER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Requirements.REQUIREMENTS.CREATOR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Requirements.REQUIREMENTS.PROJECT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getRealized();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getCreationTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getLastupdatedTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getLeadDeveloperId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getCreatorId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getProjectId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequirementsRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequirementsRecord value2(java.lang.String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequirementsRecord value3(java.lang.String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequirementsRecord value4(java.sql.Timestamp value) {
		setRealized(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequirementsRecord value5(java.sql.Timestamp value) {
		setCreationTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequirementsRecord value6(java.sql.Timestamp value) {
		setLastupdatedTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequirementsRecord value7(java.lang.Integer value) {
		setLeadDeveloperId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequirementsRecord value8(java.lang.Integer value) {
		setCreatorId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequirementsRecord value9(java.lang.Integer value) {
		setProjectId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequirementsRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.sql.Timestamp value4, java.sql.Timestamp value5, java.sql.Timestamp value6, java.lang.Integer value7, java.lang.Integer value8, java.lang.Integer value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RequirementsRecord
	 */
	public RequirementsRecord() {
		super(de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Requirements.REQUIREMENTS);
	}

	/**
	 * Create a detached, initialised RequirementsRecord
	 */
	public RequirementsRecord(java.lang.Integer id, java.lang.String title, java.lang.String description, java.sql.Timestamp realized, java.sql.Timestamp creationTime, java.sql.Timestamp lastupdatedTime, java.lang.Integer leadDeveloperId, java.lang.Integer creatorId, java.lang.Integer projectId) {
		super(de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Requirements.REQUIREMENTS);

		setValue(0, id);
		setValue(1, title);
		setValue(2, description);
		setValue(3, realized);
		setValue(4, creationTime);
		setValue(5, lastupdatedTime);
		setValue(6, leadDeveloperId);
		setValue(7, creatorId);
		setValue(8, projectId);
	}
}
