/*
 * This file is generated by jOOQ.
*/
package de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records;


import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Requirement;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RequirementRecord extends UpdatableRecordImpl<RequirementRecord> implements Record9<Integer, String, String, Timestamp, Timestamp, Timestamp, Integer, Integer, Integer> {

    private static final long serialVersionUID = 810912095;

    /**
     * Setter for <code>reqbaz.requirement.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>reqbaz.requirement.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>reqbaz.requirement.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>reqbaz.requirement.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>reqbaz.requirement.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>reqbaz.requirement.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>reqbaz.requirement.realized</code>.
     */
    public void setRealized(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>reqbaz.requirement.realized</code>.
     */
    public Timestamp getRealized() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>reqbaz.requirement.creation_time</code>.
     */
    public void setCreationTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>reqbaz.requirement.creation_time</code>.
     */
    public Timestamp getCreationTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>reqbaz.requirement.lastupdated_time</code>.
     */
    public void setLastupdatedTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>reqbaz.requirement.lastupdated_time</code>.
     */
    public Timestamp getLastupdatedTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>reqbaz.requirement.lead_developer_id</code>.
     */
    public void setLeadDeveloperId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>reqbaz.requirement.lead_developer_id</code>.
     */
    public Integer getLeadDeveloperId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>reqbaz.requirement.creator_id</code>.
     */
    public void setCreatorId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>reqbaz.requirement.creator_id</code>.
     */
    public Integer getCreatorId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>reqbaz.requirement.project_id</code>.
     */
    public void setProjectId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>reqbaz.requirement.project_id</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, Timestamp, Timestamp, Timestamp, Integer, Integer, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, Timestamp, Timestamp, Timestamp, Integer, Integer, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Requirement.REQUIREMENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Requirement.REQUIREMENT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Requirement.REQUIREMENT.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Requirement.REQUIREMENT.REALIZED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Requirement.REQUIREMENT.CREATION_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Requirement.REQUIREMENT.LASTUPDATED_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Requirement.REQUIREMENT.LEAD_DEVELOPER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Requirement.REQUIREMENT.CREATOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Requirement.REQUIREMENT.PROJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getRealized();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreationTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getLastupdatedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getLeadDeveloperId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getCreatorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RequirementRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RequirementRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RequirementRecord value3(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RequirementRecord value4(Timestamp value) {
        setRealized(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RequirementRecord value5(Timestamp value) {
        setCreationTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RequirementRecord value6(Timestamp value) {
        setLastupdatedTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RequirementRecord value7(Integer value) {
        setLeadDeveloperId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RequirementRecord value8(Integer value) {
        setCreatorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RequirementRecord value9(Integer value) {
        setProjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RequirementRecord values(Integer value1, String value2, String value3, Timestamp value4, Timestamp value5, Timestamp value6, Integer value7, Integer value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RequirementRecord
     */
    public RequirementRecord() {
        super(Requirement.REQUIREMENT);
    }

    /**
     * Create a detached, initialised RequirementRecord
     */
    public RequirementRecord(Integer id, String name, String description, Timestamp realized, Timestamp creationTime, Timestamp lastupdatedTime, Integer leadDeveloperId, Integer creatorId, Integer projectId) {
        super(Requirement.REQUIREMENT);

        set(0, id);
        set(1, name);
        set(2, description);
        set(3, realized);
        set(4, creationTime);
        set(5, lastupdatedTime);
        set(6, leadDeveloperId);
        set(7, creatorId);
        set(8, projectId);
    }
}
