/*
 * This file is generated by jOOQ.
*/
package de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records;


import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.RolePrivilegeMap;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolePrivilegeMapRecord extends UpdatableRecordImpl<RolePrivilegeMapRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = -308748188;

    /**
     * Setter for <code>reqbaz.role_privilege_map.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>reqbaz.role_privilege_map.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>reqbaz.role_privilege_map.role_id</code>.
     */
    public void setRoleId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>reqbaz.role_privilege_map.role_id</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>reqbaz.role_privilege_map.privilege_id</code>.
     */
    public void setPrivilegeId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>reqbaz.role_privilege_map.privilege_id</code>.
     */
    public Integer getPrivilegeId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RolePrivilegeMap.ROLE_PRIVILEGE_MAP.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return RolePrivilegeMap.ROLE_PRIVILEGE_MAP.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return RolePrivilegeMap.ROLE_PRIVILEGE_MAP.PRIVILEGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPrivilegeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolePrivilegeMapRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolePrivilegeMapRecord value2(Integer value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolePrivilegeMapRecord value3(Integer value) {
        setPrivilegeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolePrivilegeMapRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RolePrivilegeMapRecord
     */
    public RolePrivilegeMapRecord() {
        super(RolePrivilegeMap.ROLE_PRIVILEGE_MAP);
    }

    /**
     * Create a detached, initialised RolePrivilegeMapRecord
     */
    public RolePrivilegeMapRecord(Integer id, Integer roleId, Integer privilegeId) {
        super(RolePrivilegeMap.ROLE_PRIVILEGE_MAP);

        set(0, id);
        set(1, roleId);
        set(2, privilegeId);
    }
}
