/**
 * This class is generated by jOOQ
 */
package de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records;


import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Tags;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagsRecord extends UpdatableRecordImpl<TagsRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 661264817;

    /**
     * Setter for <code>reqbaz.tags.Id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>reqbaz.tags.Id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>reqbaz.tags.Components_Id</code>.
     */
    public void setComponentsId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>reqbaz.tags.Components_Id</code>.
     */
    public Integer getComponentsId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>reqbaz.tags.Requirements_Id</code>.
     */
    public void setRequirementsId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>reqbaz.tags.Requirements_Id</code>.
     */
    public Integer getRequirementsId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Tags.TAGS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Tags.TAGS.COMPONENTS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Tags.TAGS.REQUIREMENTS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getComponentsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getRequirementsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagsRecord value2(Integer value) {
        setComponentsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagsRecord value3(Integer value) {
        setRequirementsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagsRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TagsRecord
     */
    public TagsRecord() {
        super(Tags.TAGS);
    }

    /**
     * Create a detached, initialised TagsRecord
     */
    public TagsRecord(Integer id, Integer componentsId, Integer requirementsId) {
        super(Tags.TAGS);

        set(0, id);
        set(1, componentsId);
        set(2, requirementsId);
    }
}
