/**
 * This class is generated by jOOQ
 */
package de.rwth.dbis.acis.bazaar.service.dal.jooq;


import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Attachments;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Comments;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.ComponentFollower;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Components;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Developers;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Privileges;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.ProjectFollower;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Projects;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.RequirementFollower;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Requirements;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.RolePrivilege;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.RoleRole;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Roles;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Tags;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.UserRole;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Users;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Votes;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Reqbaz extends SchemaImpl {

	private static final long serialVersionUID = -61670257;

	/**
	 * The reference instance of <code>reqbaz</code>
	 */
	public static final Reqbaz REQBAZ = new Reqbaz();

	/**
	 * No further instances allowed
	 */
	private Reqbaz() {
		super("reqbaz");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Attachments.ATTACHMENTS,
			Comments.COMMENTS,
			Components.COMPONENTS,
			ComponentFollower.COMPONENT_FOLLOWER,
			Developers.DEVELOPERS,
			Privileges.PRIVILEGES,
			Projects.PROJECTS,
			ProjectFollower.PROJECT_FOLLOWER,
			Requirements.REQUIREMENTS,
			RequirementFollower.REQUIREMENT_FOLLOWER,
			Roles.ROLES,
			RolePrivilege.ROLE_PRIVILEGE,
			RoleRole.ROLE_ROLE,
			Tags.TAGS,
			Users.USERS,
			UserRole.USER_ROLE,
			Votes.VOTES);
	}
}
