/**
 * This class is generated by jOOQ
 */
package de.rwth.dbis.acis.bazaar.service.dal.jooq;

/**
 * This class is generated by jOOQ.
 * <p>
 * Convenience access to all tables in reqbaz
 */
@javax.annotation.Generated(value = {"http://www.jooq.org", "3.4.2"},
        comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table reqbaz.attachments
     */
    public static final de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Attachments ATTACHMENTS = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Attachments.ATTACHMENTS;

    /**
     * The table reqbaz.comments
     */
    public static final de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Comments COMMENTS = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Comments.COMMENTS;

    /**
     * The table reqbaz.components
     */
    public static final de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Components COMPONENTS = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Components.COMPONENTS;

    /**
     * The table reqbaz.developers
     */
    public static final de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Developers DEVELOPERS = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Developers.DEVELOPERS;

    /**
     * The table reqbaz.followers
     */
    public static final de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Followers FOLLOWERS = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Followers.FOLLOWERS;

    /**
     * The table reqbaz.privileges
     */
    public static final de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Privileges PRIVILEGES = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Privileges.PRIVILEGES;

    /**
     * The table reqbaz.projects
     */
    public static final de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Projects PROJECTS = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Projects.PROJECTS;

    /**
     * The table reqbaz.requirements
     */
    public static final de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Requirements REQUIREMENTS = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Requirements.REQUIREMENTS;

    /**
     * The table reqbaz.roles
     */
    public static final de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Roles ROLES = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Roles.ROLES;

    /**
     * The table reqbaz.role_privilege
     */
    public static final de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.RolePrivilege ROLE_PRIVILEGE = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.RolePrivilege.ROLE_PRIVILEGE;

    /**
     * The table reqbaz.role_role
     */
    public static final de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.RoleRole ROLE_ROLE = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.RoleRole.ROLE_ROLE;

    /**
     * The table reqbaz.tags
     */
    public static final de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Tags TAGS = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Tags.TAGS;

    /**
     * The table reqbaz.users
     */
    public static final de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Users USERS = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Users.USERS;

    /**
     * The table reqbaz.user_role
     */
    public static final de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.UserRole USER_ROLE = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.UserRole.USER_ROLE;

    /**
     * The table reqbaz.votes
     */
    public static final de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Votes VOTES = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Votes.VOTES;
}
