/**
 * This class is generated by jOOQ
 */
package de.rwth.dbis.acis.bazaar.service.dal.jooq;


import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Attachments;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Comments;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.ComponentFollower;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Components;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Developers;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Privileges;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.ProjectFollower;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Projects;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.RequirementFollower;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Requirements;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.RolePrivilege;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.RoleRole;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Roles;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Tags;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.UserRole;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Users;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Votes;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in reqbaz
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>reqbaz.attachments</code>.
     */
    public static final Attachments ATTACHMENTS = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Attachments.ATTACHMENTS;

    /**
     * The table <code>reqbaz.comments</code>.
     */
    public static final Comments COMMENTS = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Comments.COMMENTS;

    /**
     * The table <code>reqbaz.components</code>.
     */
    public static final Components COMPONENTS = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Components.COMPONENTS;

    /**
     * The table <code>reqbaz.component_follower</code>.
     */
    public static final ComponentFollower COMPONENT_FOLLOWER = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.ComponentFollower.COMPONENT_FOLLOWER;

    /**
     * The table <code>reqbaz.developers</code>.
     */
    public static final Developers DEVELOPERS = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Developers.DEVELOPERS;

    /**
     * The table <code>reqbaz.privileges</code>.
     */
    public static final Privileges PRIVILEGES = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Privileges.PRIVILEGES;

    /**
     * The table <code>reqbaz.projects</code>.
     */
    public static final Projects PROJECTS = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Projects.PROJECTS;

    /**
     * The table <code>reqbaz.project_follower</code>.
     */
    public static final ProjectFollower PROJECT_FOLLOWER = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.ProjectFollower.PROJECT_FOLLOWER;

    /**
     * The table <code>reqbaz.requirements</code>.
     */
    public static final Requirements REQUIREMENTS = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Requirements.REQUIREMENTS;

    /**
     * The table <code>reqbaz.requirement_follower</code>.
     */
    public static final RequirementFollower REQUIREMENT_FOLLOWER = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.RequirementFollower.REQUIREMENT_FOLLOWER;

    /**
     * The table <code>reqbaz.roles</code>.
     */
    public static final Roles ROLES = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Roles.ROLES;

    /**
     * The table <code>reqbaz.role_privilege</code>.
     */
    public static final RolePrivilege ROLE_PRIVILEGE = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.RolePrivilege.ROLE_PRIVILEGE;

    /**
     * The table <code>reqbaz.role_role</code>.
     */
    public static final RoleRole ROLE_ROLE = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.RoleRole.ROLE_ROLE;

    /**
     * The table <code>reqbaz.tags</code>.
     */
    public static final Tags TAGS = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Tags.TAGS;

    /**
     * The table <code>reqbaz.users</code>.
     */
    public static final Users USERS = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Users.USERS;

    /**
     * The table <code>reqbaz.user_role</code>.
     */
    public static final UserRole USER_ROLE = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.UserRole.USER_ROLE;

    /**
     * The table <code>reqbaz.votes</code>.
     */
    public static final Votes VOTES = de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Votes.VOTES;
}
