/**
 * This class is generated by jOOQ
 */
package de.rwth.dbis.acis.bazaar.dal.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AttachementsRecord extends org.jooq.impl.UpdatableRecordImpl<de.rwth.dbis.acis.bazaar.dal.jooq.tables.records.AttachementsRecord> implements org.jooq.Record4<java.lang.Integer, java.sql.Timestamp, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -1408985975;

	/**
	 * Setter for <code>reqbaz.attachements.Id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>reqbaz.attachements.Id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>reqbaz.attachements.creation_time</code>.
	 */
	public void setCreationTime(java.sql.Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>reqbaz.attachements.creation_time</code>.
	 */
	public java.sql.Timestamp getCreationTime() {
		return (java.sql.Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>reqbaz.attachements.Requirement_Id</code>.
	 */
	public void setRequirementId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>reqbaz.attachements.Requirement_Id</code>.
	 */
	public java.lang.Integer getRequirementId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>reqbaz.attachements.User_Id</code>.
	 */
	public void setUserId(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>reqbaz.attachements.User_Id</code>.
	 */
	public java.lang.Integer getUserId() {
		return (java.lang.Integer) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.sql.Timestamp, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.sql.Timestamp, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return de.rwth.dbis.acis.bazaar.dal.jooq.tables.Attachements.ATTACHEMENTS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field2() {
		return de.rwth.dbis.acis.bazaar.dal.jooq.tables.Attachements.ATTACHEMENTS.CREATION_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return de.rwth.dbis.acis.bazaar.dal.jooq.tables.Attachements.ATTACHEMENTS.REQUIREMENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return de.rwth.dbis.acis.bazaar.dal.jooq.tables.Attachements.ATTACHEMENTS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value2() {
		return getCreationTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getRequirementId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttachementsRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttachementsRecord value2(java.sql.Timestamp value) {
		setCreationTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttachementsRecord value3(java.lang.Integer value) {
		setRequirementId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttachementsRecord value4(java.lang.Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttachementsRecord values(java.lang.Integer value1, java.sql.Timestamp value2, java.lang.Integer value3, java.lang.Integer value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AttachementsRecord
	 */
	public AttachementsRecord() {
		super(de.rwth.dbis.acis.bazaar.dal.jooq.tables.Attachements.ATTACHEMENTS);
	}

	/**
	 * Create a detached, initialised AttachementsRecord
	 */
	public AttachementsRecord(java.lang.Integer id, java.sql.Timestamp creationTime, java.lang.Integer requirementId, java.lang.Integer userId) {
		super(de.rwth.dbis.acis.bazaar.dal.jooq.tables.Attachements.ATTACHEMENTS);

		setValue(0, id);
		setValue(1, creationTime);
		setValue(2, requirementId);
		setValue(3, userId);
	}
}
