/**
 * This class is generated by jOOQ
 */
package de.rwth.dbis.acis.bazaar.dal.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends org.jooq.impl.UpdatableRecordImpl<de.rwth.dbis.acis.bazaar.dal.jooq.tables.records.UsersRecord> implements org.jooq.Record9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Byte, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1316685905;

	/**
	 * Setter for <code>reqbaz.users.Id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>reqbaz.users.Id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>reqbaz.users.frist_name</code>.
	 */
	public void setFristName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>reqbaz.users.frist_name</code>.
	 */
	public java.lang.String getFristName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>reqbaz.users.last_name</code>.
	 */
	public void setLastName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>reqbaz.users.last_name</code>.
	 */
	public java.lang.String getLastName() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>reqbaz.users.email</code>.
	 */
	public void setEmail(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>reqbaz.users.email</code>.
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>reqbaz.users.admin</code>.
	 */
	public void setAdmin(java.lang.Byte value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>reqbaz.users.admin</code>.
	 */
	public java.lang.Byte getAdmin() {
		return (java.lang.Byte) getValue(4);
	}

	/**
	 * Setter for <code>reqbaz.users.User_Id</code>.
	 */
	public void setUserId(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>reqbaz.users.User_Id</code>.
	 */
	public java.lang.Integer getUserId() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>reqbaz.users.user_name</code>.
	 */
	public void setUserName(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>reqbaz.users.user_name</code>.
	 */
	public java.lang.String getUserName() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>reqbaz.users.openId_iss</code>.
	 */
	public void setOpenidIss(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>reqbaz.users.openId_iss</code>.
	 */
	public java.lang.String getOpenidIss() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>reqbaz.users.openId_sub</code>.
	 */
	public void setOpenidSub(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>reqbaz.users.openId_sub</code>.
	 */
	public java.lang.String getOpenidSub() {
		return (java.lang.String) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Byte, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Byte, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return de.rwth.dbis.acis.bazaar.dal.jooq.tables.Users.USERS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return de.rwth.dbis.acis.bazaar.dal.jooq.tables.Users.USERS.FRIST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return de.rwth.dbis.acis.bazaar.dal.jooq.tables.Users.USERS.LAST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return de.rwth.dbis.acis.bazaar.dal.jooq.tables.Users.USERS.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field5() {
		return de.rwth.dbis.acis.bazaar.dal.jooq.tables.Users.USERS.ADMIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return de.rwth.dbis.acis.bazaar.dal.jooq.tables.Users.USERS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return de.rwth.dbis.acis.bazaar.dal.jooq.tables.Users.USERS.USER_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return de.rwth.dbis.acis.bazaar.dal.jooq.tables.Users.USERS.OPENID_ISS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return de.rwth.dbis.acis.bazaar.dal.jooq.tables.Users.USERS.OPENID_SUB;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getFristName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getLastName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value5() {
		return getAdmin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getUserName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getOpenidIss();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getOpenidSub();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value2(java.lang.String value) {
		setFristName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value3(java.lang.String value) {
		setLastName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value4(java.lang.String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value5(java.lang.Byte value) {
		setAdmin(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value6(java.lang.Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value7(java.lang.String value) {
		setUserName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value8(java.lang.String value) {
		setOpenidIss(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value9(java.lang.String value) {
		setOpenidSub(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.Byte value5, java.lang.Integer value6, java.lang.String value7, java.lang.String value8, java.lang.String value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UsersRecord
	 */
	public UsersRecord() {
		super(de.rwth.dbis.acis.bazaar.dal.jooq.tables.Users.USERS);
	}

	/**
	 * Create a detached, initialised UsersRecord
	 */
	public UsersRecord(java.lang.Integer id, java.lang.String fristName, java.lang.String lastName, java.lang.String email, java.lang.Byte admin, java.lang.Integer userId, java.lang.String userName, java.lang.String openidIss, java.lang.String openidSub) {
		super(de.rwth.dbis.acis.bazaar.dal.jooq.tables.Users.USERS);

		setValue(0, id);
		setValue(1, fristName);
		setValue(2, lastName);
		setValue(3, email);
		setValue(4, admin);
		setValue(5, userId);
		setValue(6, userName);
		setValue(7, openidIss);
		setValue(8, openidSub);
	}
}
