/**
 * This class is generated by jOOQ
 */
package de.rwth.dbis.acis.bazaar.service.dal.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value = {"http://www.jooq.org", "3.4.2"},
        comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Followers extends org.jooq.impl.TableImpl<de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records.FollowersRecord> {

    private static final long serialVersionUID = -1574948115;

    /**
     * The singleton instance of <code>reqbaz.followers</code>
     */
    public static final de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Followers FOLLOWERS = new de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Followers();

    /**
     * The class holding records for this type
     */
    @Override
    public java.lang.Class<de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records.FollowersRecord> getRecordType() {
        return de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records.FollowersRecord.class;
    }

    /**
     * The column <code>reqbaz.followers.Id</code>.
     */
    public final org.jooq.TableField<de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records.FollowersRecord, java.lang.Integer> ID = createField("Id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>reqbaz.followers.Requirement_Id</code>.
     */
    public final org.jooq.TableField<de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records.FollowersRecord, java.lang.Integer> REQUIREMENT_ID = createField("Requirement_Id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>reqbaz.followers.User_Id</code>.
     */
    public final org.jooq.TableField<de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records.FollowersRecord, java.lang.Integer> USER_ID = createField("User_Id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>reqbaz.followers.creation_time</code>.
     */
    public final org.jooq.TableField<de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records.FollowersRecord, java.sql.Timestamp> CREATION_TIME = createField("creation_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

    /**
     * Create a <code>reqbaz.followers</code> table reference
     */
    public Followers() {
        this("followers", null);
    }

    /**
     * Create an aliased <code>reqbaz.followers</code> table reference
     */
    public Followers(java.lang.String alias) {
        this(alias, de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Followers.FOLLOWERS);
    }

    private Followers(java.lang.String alias, org.jooq.Table<de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records.FollowersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Followers(java.lang.String alias, org.jooq.Table<de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records.FollowersRecord> aliased, org.jooq.Field<?>[] parameters) {
        super(alias, de.rwth.dbis.acis.bazaar.service.dal.jooq.Reqbaz.REQBAZ, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Identity<de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records.FollowersRecord, java.lang.Integer> getIdentity() {
        return de.rwth.dbis.acis.bazaar.service.dal.jooq.Keys.IDENTITY_FOLLOWERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.UniqueKey<de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records.FollowersRecord> getPrimaryKey() {
        return de.rwth.dbis.acis.bazaar.service.dal.jooq.Keys.KEY_FOLLOWERS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.util.List<org.jooq.UniqueKey<de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records.FollowersRecord>> getKeys() {
        return java.util.Arrays.<org.jooq.UniqueKey<de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records.FollowersRecord>>asList(de.rwth.dbis.acis.bazaar.service.dal.jooq.Keys.KEY_FOLLOWERS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.util.List<org.jooq.ForeignKey<de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records.FollowersRecord, ?>> getReferences() {
        return java.util.Arrays.<org.jooq.ForeignKey<de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records.FollowersRecord, ?>>asList(de.rwth.dbis.acis.bazaar.service.dal.jooq.Keys.FOLLOWER_REQUIREMENT, de.rwth.dbis.acis.bazaar.service.dal.jooq.Keys.FOLLOWER_USER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Followers as(java.lang.String alias) {
        return new de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Followers(alias, this);
    }

    /**
     * Rename this table
     */
    public de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Followers rename(java.lang.String name) {
        return new de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.Followers(name, null);
    }
}
