/**
 * This class is generated by jOOQ
 */
package de.rwth.dbis.acis.bazaar.service.dal.jooq.tables;


import de.rwth.dbis.acis.bazaar.service.dal.jooq.Keys;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.Reqbaz;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records.PrivilegesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Privileges extends TableImpl<PrivilegesRecord> {

	private static final long serialVersionUID = -535550246;

	/**
	 * The reference instance of <code>reqbaz.privileges</code>
	 */
	public static final Privileges PRIVILEGES = new Privileges();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PrivilegesRecord> getRecordType() {
		return PrivilegesRecord.class;
	}

	/**
	 * The column <code>reqbaz.privileges.Id</code>.
	 */
	public final TableField<PrivilegesRecord, Integer> ID = createField("Id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>reqbaz.privileges.name</code>.
	 */
	public final TableField<PrivilegesRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * Create a <code>reqbaz.privileges</code> table reference
	 */
	public Privileges() {
		this("privileges", null);
	}

	/**
	 * Create an aliased <code>reqbaz.privileges</code> table reference
	 */
	public Privileges(String alias) {
		this(alias, PRIVILEGES);
	}

	private Privileges(String alias, Table<PrivilegesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Privileges(String alias, Table<PrivilegesRecord> aliased, Field<?>[] parameters) {
		super(alias, Reqbaz.REQBAZ, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<PrivilegesRecord, Integer> getIdentity() {
		return Keys.IDENTITY_PRIVILEGES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PrivilegesRecord> getPrimaryKey() {
		return Keys.KEY_PRIVILEGES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PrivilegesRecord>> getKeys() {
		return Arrays.<UniqueKey<PrivilegesRecord>>asList(Keys.KEY_PRIVILEGES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Privileges as(String alias) {
		return new Privileges(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Privileges rename(String name) {
		return new Privileges(name, null);
	}
}
