/*
 * This file is generated by jOOQ.
*/
package de.rwth.dbis.acis.bazaar.service.dal.jooq.tables;


import de.rwth.dbis.acis.bazaar.service.dal.jooq.Keys;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.Reqbaz;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records.RequirementComponentMapRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RequirementComponentMap extends TableImpl<RequirementComponentMapRecord> {

    private static final long serialVersionUID = 825561647;

    /**
     * The reference instance of <code>reqbaz.requirement_component_map</code>
     */
    public static final RequirementComponentMap REQUIREMENT_COMPONENT_MAP = new RequirementComponentMap();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RequirementComponentMapRecord> getRecordType() {
        return RequirementComponentMapRecord.class;
    }

    /**
     * The column <code>reqbaz.requirement_component_map.id</code>.
     */
    public final TableField<RequirementComponentMapRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>reqbaz.requirement_component_map.component_id</code>.
     */
    public final TableField<RequirementComponentMapRecord, Integer> COMPONENT_ID = createField("component_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>reqbaz.requirement_component_map.requirement_id</code>.
     */
    public final TableField<RequirementComponentMapRecord, Integer> REQUIREMENT_ID = createField("requirement_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>reqbaz.requirement_component_map</code> table reference
     */
    public RequirementComponentMap() {
        this("requirement_component_map", null);
    }

    /**
     * Create an aliased <code>reqbaz.requirement_component_map</code> table reference
     */
    public RequirementComponentMap(String alias) {
        this(alias, REQUIREMENT_COMPONENT_MAP);
    }

    private RequirementComponentMap(String alias, Table<RequirementComponentMapRecord> aliased) {
        this(alias, aliased, null);
    }

    private RequirementComponentMap(String alias, Table<RequirementComponentMapRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Reqbaz.REQBAZ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RequirementComponentMapRecord, Integer> getIdentity() {
        return Keys.IDENTITY_REQUIREMENT_COMPONENT_MAP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RequirementComponentMapRecord> getPrimaryKey() {
        return Keys.KEY_REQUIREMENT_COMPONENT_MAP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RequirementComponentMapRecord>> getKeys() {
        return Arrays.<UniqueKey<RequirementComponentMapRecord>>asList(Keys.KEY_REQUIREMENT_COMPONENT_MAP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RequirementComponentMapRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RequirementComponentMapRecord, ?>>asList(Keys.REQUIREMENT_COMPONENT_MAP_COMPONENT, Keys.REQUIREMENT_COMPONENT_MAP_REQUIREMENT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RequirementComponentMap as(String alias) {
        return new RequirementComponentMap(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RequirementComponentMap rename(String name) {
        return new RequirementComponentMap(name, null);
    }
}
