/**
 * This class is generated by jOOQ
 */
package de.rwth.dbis.acis.bazaar.service.dal.jooq.tables;


import de.rwth.dbis.acis.bazaar.service.dal.jooq.Keys;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.Reqbaz;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records.RequirementFollowerRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RequirementFollower extends TableImpl<RequirementFollowerRecord> {

	private static final long serialVersionUID = -1509754035;

	/**
	 * The reference instance of <code>reqbaz.requirement_follower</code>
	 */
	public static final RequirementFollower REQUIREMENT_FOLLOWER = new RequirementFollower();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RequirementFollowerRecord> getRecordType() {
		return RequirementFollowerRecord.class;
	}

	/**
	 * The column <code>reqbaz.requirement_follower.Id</code>.
	 */
	public final TableField<RequirementFollowerRecord, Integer> ID = createField("Id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>reqbaz.requirement_follower.Requirement_Id</code>.
	 */
	public final TableField<RequirementFollowerRecord, Integer> REQUIREMENT_ID = createField("Requirement_Id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>reqbaz.requirement_follower.User_Id</code>.
	 */
	public final TableField<RequirementFollowerRecord, Integer> USER_ID = createField("User_Id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>reqbaz.requirement_follower.creation_time</code>.
	 */
	public final TableField<RequirementFollowerRecord, Timestamp> CREATION_TIME = createField("creation_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>reqbaz.requirement_follower</code> table reference
	 */
	public RequirementFollower() {
		this("requirement_follower", null);
	}

	/**
	 * Create an aliased <code>reqbaz.requirement_follower</code> table reference
	 */
	public RequirementFollower(String alias) {
		this(alias, REQUIREMENT_FOLLOWER);
	}

	private RequirementFollower(String alias, Table<RequirementFollowerRecord> aliased) {
		this(alias, aliased, null);
	}

	private RequirementFollower(String alias, Table<RequirementFollowerRecord> aliased, Field<?>[] parameters) {
		super(alias, Reqbaz.REQBAZ, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<RequirementFollowerRecord, Integer> getIdentity() {
		return Keys.IDENTITY_REQUIREMENT_FOLLOWER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<RequirementFollowerRecord> getPrimaryKey() {
		return Keys.KEY_REQUIREMENT_FOLLOWER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<RequirementFollowerRecord>> getKeys() {
		return Arrays.<UniqueKey<RequirementFollowerRecord>>asList(Keys.KEY_REQUIREMENT_FOLLOWER_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<RequirementFollowerRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<RequirementFollowerRecord, ?>>asList(Keys.REQUIREMENT_FOLLOWER, Keys.REQUIREMENT_FOLLOWER_USER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequirementFollower as(String alias) {
		return new RequirementFollower(alias, this);
	}

	/**
	 * Rename this table
	 */
	public RequirementFollower rename(String name) {
		return new RequirementFollower(name, null);
	}
}
