/*
 * This file is generated by jOOQ.
 */
package de.rwth.dbis.acis.bazaar.service.dal.jooq.tables;


import de.rwth.dbis.acis.bazaar.service.dal.jooq.Keys;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.Reqbaz;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records.RolePrivilegeMapRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RolePrivilegeMap extends TableImpl<RolePrivilegeMapRecord> {

    private static final long serialVersionUID = 288946433;

    /**
     * The reference instance of <code>reqbaz.role_privilege_map</code>
     */
    public static final RolePrivilegeMap ROLE_PRIVILEGE_MAP = new RolePrivilegeMap();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RolePrivilegeMapRecord> getRecordType() {
        return RolePrivilegeMapRecord.class;
    }

    /**
     * The column <code>reqbaz.role_privilege_map.id</code>.
     */
    public final TableField<RolePrivilegeMapRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>reqbaz.role_privilege_map.role_id</code>.
     */
    public final TableField<RolePrivilegeMapRecord, Integer> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>reqbaz.role_privilege_map.privilege_id</code>.
     */
    public final TableField<RolePrivilegeMapRecord, Integer> PRIVILEGE_ID = createField("privilege_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>reqbaz.role_privilege_map</code> table reference
     */
    public RolePrivilegeMap() {
        this("role_privilege_map", null);
    }

    /**
     * Create an aliased <code>reqbaz.role_privilege_map</code> table reference
     */
    public RolePrivilegeMap(String alias) {
        this(alias, ROLE_PRIVILEGE_MAP);
    }

    private RolePrivilegeMap(String alias, Table<RolePrivilegeMapRecord> aliased) {
        this(alias, aliased, null);
    }

    private RolePrivilegeMap(String alias, Table<RolePrivilegeMapRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Reqbaz.REQBAZ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RolePrivilegeMapRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ROLE_PRIVILEGE_MAP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RolePrivilegeMapRecord> getPrimaryKey() {
        return Keys.KEY_ROLE_PRIVILEGE_MAP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RolePrivilegeMapRecord>> getKeys() {
        return Arrays.<UniqueKey<RolePrivilegeMapRecord>>asList(Keys.KEY_ROLE_PRIVILEGE_MAP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RolePrivilegeMapRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RolePrivilegeMapRecord, ?>>asList(Keys.ROLE_PRIVILEGE_MAP_ROLE, Keys.ROLE_PRIVILEGE_MAP_PRIVILEGE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolePrivilegeMap as(String alias) {
        return new RolePrivilegeMap(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RolePrivilegeMap rename(String name) {
        return new RolePrivilegeMap(name, null);
    }
}
