/**
 * This class is generated by jOOQ
 */
package de.rwth.dbis.acis.bazaar.service.dal.jooq.tables;


import de.rwth.dbis.acis.bazaar.service.dal.jooq.Keys;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.Reqbaz;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records.RolesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Roles extends TableImpl<RolesRecord> {

	private static final long serialVersionUID = -356774375;

	/**
	 * The reference instance of <code>reqbaz.roles</code>
	 */
	public static final Roles ROLES = new Roles();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RolesRecord> getRecordType() {
		return RolesRecord.class;
	}

	/**
	 * The column <code>reqbaz.roles.Id</code>.
	 */
	public final TableField<RolesRecord, Integer> ID = createField("Id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>reqbaz.roles.name</code>.
	 */
	public final TableField<RolesRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * Create a <code>reqbaz.roles</code> table reference
	 */
	public Roles() {
		this("roles", null);
	}

	/**
	 * Create an aliased <code>reqbaz.roles</code> table reference
	 */
	public Roles(String alias) {
		this(alias, ROLES);
	}

	private Roles(String alias, Table<RolesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Roles(String alias, Table<RolesRecord> aliased, Field<?>[] parameters) {
		super(alias, Reqbaz.REQBAZ, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<RolesRecord, Integer> getIdentity() {
		return Keys.IDENTITY_ROLES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<RolesRecord> getPrimaryKey() {
		return Keys.KEY_ROLES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<RolesRecord>> getKeys() {
		return Arrays.<UniqueKey<RolesRecord>>asList(Keys.KEY_ROLES_PRIMARY, Keys.KEY_ROLES_ROLE_IDX_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Roles as(String alias) {
		return new Roles(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Roles rename(String name) {
		return new Roles(name, null);
	}
}
