/*
 * This file is generated by jOOQ.
 */
package de.rwth.dbis.acis.bazaar.service.dal.jooq.tables;


import de.rwth.dbis.acis.bazaar.service.dal.jooq.Keys;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.Reqbaz;
import de.rwth.dbis.acis.bazaar.service.dal.jooq.tables.records.UserRoleMapRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class UserRoleMap extends TableImpl<UserRoleMapRecord> {

    private static final long serialVersionUID = 902266899;

    /**
     * The reference instance of <code>reqbaz.user_role_map</code>
     */
    public static final UserRoleMap USER_ROLE_MAP = new UserRoleMap();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserRoleMapRecord> getRecordType() {
        return UserRoleMapRecord.class;
    }

    /**
     * The column <code>reqbaz.user_role_map.id</code>.
     */
    public final TableField<UserRoleMapRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>reqbaz.user_role_map.role_id</code>.
     */
    public final TableField<UserRoleMapRecord, Integer> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>reqbaz.user_role_map.user_id</code>.
     */
    public final TableField<UserRoleMapRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>reqbaz.user_role_map.context_info</code>.
     */
    public final TableField<UserRoleMapRecord, String> CONTEXT_INFO = createField("context_info", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * Create a <code>reqbaz.user_role_map</code> table reference
     */
    public UserRoleMap() {
        this("user_role_map", null);
    }

    /**
     * Create an aliased <code>reqbaz.user_role_map</code> table reference
     */
    public UserRoleMap(String alias) {
        this(alias, USER_ROLE_MAP);
    }

    private UserRoleMap(String alias, Table<UserRoleMapRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserRoleMap(String alias, Table<UserRoleMapRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Reqbaz.REQBAZ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UserRoleMapRecord, Integer> getIdentity() {
        return Keys.IDENTITY_USER_ROLE_MAP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserRoleMapRecord> getPrimaryKey() {
        return Keys.KEY_USER_ROLE_MAP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserRoleMapRecord>> getKeys() {
        return Arrays.<UniqueKey<UserRoleMapRecord>>asList(Keys.KEY_USER_ROLE_MAP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<UserRoleMapRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserRoleMapRecord, ?>>asList(Keys.USER_ROLE_MAP_ROLE, Keys.USER_ROLE_MAP_USER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRoleMap as(String alias) {
        return new UserRoleMap(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserRoleMap rename(String name) {
        return new UserRoleMap(name, null);
    }
}
